<?php
namespace Converge\Dolittle\Tests\Message\Body;

use \Converge\Dolittle\Message\Body\Response;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-08-21 at 21:04:47.
 */
class ResponseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Response
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new Response;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    public function testConstruct()
    {
        $this->assertTrue(true);
    }
}
