<?php
namespace Converge\Dolittle\Tests;

use \Converge\Dolittle\Client;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-08-21 at 21:01:26.
 */
class ClientTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Client
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getMockBuilder('Client')
            ->setMethods(array('__construct'))
            ->setConstructorArgs(array('connection_info'))
            ->disableOriginalConstructor()
            ->getMock();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    public function testExecuteScript()
    {
        $this->assertTrue(true);
    }
    
    public function testGetResponse()
    {
        $this->assertTrue(true);
    }
    
    public function testSend()
    {
        $this->assertTrue(true);
    }
    
    public function testDestroy()
    {
        $this->assertTrue(true);
    }
}
