<?php
namespace Converge\Dolittle\Tests;

use \Converge\Dolittle\Exception;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-08-21 at 21:02:12.
 */
class ExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Exception
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Exception('My Error Message');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    public function testConstruct()
    {
        $this->assertEquals('My Error Message', $this->object->getMessage());
    }
}
