<?php
namespace Converge\Dolittle\Tests;

use \Converge\Dolittle\Message;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-08-21 at 20:34:46.
 */
class MessageTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Message
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Message;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    public function testSetProtocolVersion()
    {
        $this->assertTrue(true);
    }
    
    public function testGetProtocolVersion()
    {
        $this->assertTrue(true);
    }
    
    public function testSetSerializerType()
    {
        $this->assertTrue(true);
    }

    public function testGetSerializerType()
    {
        $this->assertTrue(true);
    }

    public function testSetMessageSize()
    {
        $this->assertTrue(true);
    }

    public function testGetMessageSize()
    {
        $this->assertTrue(true);
    }

    public function testSetMessageType()
    {
        $this->assertTrue(true);
    }
    
    public function testGetMessageType()
    {
        $this->assertTrue(true);
    }
    
    public function testSetMessageBody()
    {
        $this->assertTrue(true);
    }
    
    public function testGetMessageBody()
    {
        $this->assertTrue(true);
    }
    
    public function testSetMessageBodySerialized()
    {
        $this->assertTrue(true);
    }
    
    public function testGetMessageBodySerialized()
    {
        $this->assertTrue(true);
    }
    
    public function testPack()
    {
        $this->assertTrue(true);
    }
    
    public function testUnpack()
    {
        $this->assertTrue(true);
    }
}
