<?php
namespace Converge\Dolittle\Tests\Message\Body\Response;

use \Converge\Dolittle\Message\Body\Response\Error;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-08-21 at 21:05:33.
 */
class ErrorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Error
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Error;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    public function testDestroy()
    {
        $this->assertTrue(true);
    }
    
    public function testSetErrorMessage()
    {
        $this->assertTrue(true);
    }
    
    public function testGetErrorMessage()
    {
        $this->assertTrue(true);
    }
    
    public function testToArray()
    {
        $this->assertTrue(true);
    }
}
