<?php
namespace Converge\Dolittle\Tests\Message;

use \Converge\Dolittle\Message\Body;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-08-21 at 21:03:29.
 */
class BodyTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Body
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new Body;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    public function testSetSession()
    {
        $this->assertTrue(true);
    }
    
    public function testGetSession()
    {
        $this->assertTrue(true);
    }
    
    public function testSetRequest()
    {
        $this->assertTrue(true);
    }
    
    public function testGetRequest()
    {
        $this->assertTrue(true);
    }
    
    public function testSetMeta()
    {
        $this->assertTrue(true);
    }
    
    public function testGetMeta()
    {
        $this->assertTrue(true);
    }
}
