<?php
namespace Converge\Dolittle\Tests\Message\Body\Request;

use \Converge\Dolittle\Message\Body\Request\Script;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-08-21 at 20:49:11.
 */
class ScriptTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Script
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Script;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    public function testSetLanguageName()
    {
        $this->assertTrue(true);
    }
    
    public function testGetLanguageName()
    {
        $this->assertTrue(true);
    }
    
    public function testSetScript()
    {
        $this->assertTrue(true);
    }
    
    public function testGetScript()
    {
        $this->assertTrue(true);
    }
    
    public function testSetBindings()
    {
        $this->assertTrue(true);
    }
    
    public function testGetBindings()
    {
        $this->assertTrue(true);
    }
    
    public function testToArray()
    {
        $this->assertTrue(true);
    }
}
